ALTER TABLE teachers ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE students ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE classes ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE guardians ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE medical_records ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE student_guardians ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE class_enrollments ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE attendance ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE subjects ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE teacher_subjects ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE teacher_classes ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE teacher_qualifications ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE teacher_documents ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE class_subjects ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE class_timetable_slots ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE student_documents ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE school_houses ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE zimsec_exam_entries ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE assignments ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE assignment_submissions ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE assessments ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE assessment_scores ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE announcements ADD COLUMN school_id INTEGER REFERENCES schools(id);
ALTER TABLE subject_resources ADD COLUMN school_id INTEGER REFERENCES schools(id);

UPDATE teachers SET school_id = (SELECT school_id FROM users WHERE users.id = teachers.user_id) WHERE school_id IS NULL;
UPDATE students SET school_id = (SELECT school_id FROM users WHERE users.id = students.user_id) WHERE school_id IS NULL;
UPDATE classes SET school_id = COALESCE((SELECT school_id FROM teachers WHERE teachers.id = classes.teacher_id), (SELECT id FROM schools WHERE code = 'SMSDEMO')) WHERE school_id IS NULL;
UPDATE guardians SET school_id = (SELECT id FROM schools WHERE code = 'SMSDEMO') WHERE school_id IS NULL;
UPDATE medical_records SET school_id = (SELECT school_id FROM students WHERE students.id = medical_records.student_id) WHERE school_id IS NULL;
UPDATE student_guardians SET school_id = (SELECT school_id FROM students WHERE students.id = student_guardians.student_id) WHERE school_id IS NULL;
UPDATE class_enrollments SET school_id = (SELECT school_id FROM classes WHERE classes.id = class_enrollments.class_id) WHERE school_id IS NULL;
UPDATE attendance SET school_id = (SELECT school_id FROM classes WHERE classes.id = attendance.class_id) WHERE school_id IS NULL;
UPDATE subjects SET school_id = (SELECT id FROM schools WHERE code = 'SMSDEMO') WHERE school_id IS NULL;
UPDATE teacher_subjects SET school_id = (SELECT school_id FROM teachers WHERE teachers.id = teacher_subjects.teacher_id) WHERE school_id IS NULL;
UPDATE teacher_classes SET school_id = (SELECT school_id FROM teachers WHERE teachers.id = teacher_classes.teacher_id) WHERE school_id IS NULL;
UPDATE teacher_qualifications SET school_id = (SELECT school_id FROM teachers WHERE teachers.id = teacher_qualifications.teacher_id) WHERE school_id IS NULL;
UPDATE teacher_documents SET school_id = (SELECT school_id FROM teachers WHERE teachers.id = teacher_documents.teacher_id) WHERE school_id IS NULL;
UPDATE class_subjects SET school_id = (SELECT school_id FROM classes WHERE classes.id = class_subjects.class_id) WHERE school_id IS NULL;
UPDATE class_timetable_slots SET school_id = (SELECT school_id FROM classes WHERE classes.id = class_timetable_slots.class_id) WHERE school_id IS NULL;
UPDATE student_documents SET school_id = (SELECT school_id FROM students WHERE students.id = student_documents.student_id) WHERE school_id IS NULL;
UPDATE school_houses SET school_id = (SELECT id FROM schools WHERE code = 'SMSDEMO') WHERE school_id IS NULL;
UPDATE zimsec_exam_entries SET school_id = (SELECT school_id FROM students WHERE students.id = zimsec_exam_entries.student_id) WHERE school_id IS NULL;
UPDATE assignments SET school_id = (SELECT school_id FROM classes WHERE classes.id = assignments.class_id) WHERE school_id IS NULL;
UPDATE assignment_submissions SET school_id = (SELECT school_id FROM students WHERE students.id = assignment_submissions.student_id) WHERE school_id IS NULL;
UPDATE assessments SET school_id = (SELECT school_id FROM classes WHERE classes.id = assessments.class_id) WHERE school_id IS NULL;
UPDATE assessment_scores SET school_id = (SELECT school_id FROM students WHERE students.id = assessment_scores.student_id) WHERE school_id IS NULL;
UPDATE announcements SET school_id = COALESCE((SELECT school_id FROM classes WHERE classes.id = announcements.class_id), (SELECT id FROM schools WHERE code = 'SMSDEMO')) WHERE school_id IS NULL;
UPDATE subject_resources SET school_id = (SELECT school_id FROM classes WHERE classes.id = subject_resources.class_id) WHERE school_id IS NULL;

CREATE INDEX IF NOT EXISTS idx_teachers_school_id ON teachers(school_id);
CREATE INDEX IF NOT EXISTS idx_students_school_id ON students(school_id);
CREATE INDEX IF NOT EXISTS idx_classes_school_id ON classes(school_id);
CREATE INDEX IF NOT EXISTS idx_attendance_school_id ON attendance(school_id);
CREATE INDEX IF NOT EXISTS idx_assignments_school_id ON assignments(school_id);
CREATE INDEX IF NOT EXISTS idx_announcements_school_id ON announcements(school_id);
